[package]
name = "httpserver"
version = "0.1.0"
edition = "2024"

[dependencies]
http = { path = "../http" }
serde = {version = "1.0.117", features = ["derive"]}
serde_json = "1.0.59"
tokio = { version = "1.0", features = ["full"] }
